// One-shot: insert analytics (an.*) i18n keys before the closing `};` of the
// translations object. Run with: node scripts/add-an-keys.mjs
// Idempotency guard: aborts if an.title already present.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const file = join(here, "..", "lib", "i18n", "translations.ts");
const src = readFileSync(file, "utf8");

if (src.includes('"an.title"')) {
  console.error("an.title already present — aborting (idempotency guard).");
  process.exit(1);
}

const BLOCK = `
  // --- Analytics (page 4) ---
  "an.title": { th: "วิเคราะห์สมองเชิงยาว", en: "Longitudinal Brain Analytics" },
  "an.subtitle": { th: "ตัวชี้วัดภาวะหมดไฟ ความซึมเศร้า และการเสื่อมถอยทางปัญญาตามเวลา", en: "Burnout, depression, and cognitive-decline markers over time" },
  "an.liveTag": { th: "แนวโน้ม 30 วัน · สด", en: "30-day trend · live" },
  "an.chart.burnout": { th: "ความเสี่ยงภาวะหมดไฟและความเหนื่อยล้าเรื้อรัง", en: "Burnout & Chronic Fatigue Risk" },
  "an.chart.burnoutSub": { th: "คะแนนความเสี่ยงรวม 0–100", en: "Composite risk score, 0–100" },
  "an.chart.faa": { th: "ความไม่สมมาตรของอัลฟาส่วนหน้า (FAA)", en: "Frontal Alpha Asymmetry (FAA)" },
  "an.chart.faaSub": { th: "ตัวชี้วัดความเสี่ยงซึมเศร้า", en: "Depression-risk indicator" },
  "an.chart.spindle": { th: "ความหนาแน่นของ Sleep Spindle", en: "Sleep Spindle Density" },
  "an.chart.spindleSub": { th: "Spindle/นาที · ตัวชี้ระยะเริ่มต้นของการเสื่อมถอยทางปัญญา", en: "Spindles/min · early cognitive-decline marker" },
  "an.chart.sws": { th: "การนอนคลื่นช้า (Slow-Wave Sleep)", en: "Slow-Wave Sleep" },
  "an.chart.swsSub": { th: "% ของการนอนทั้งหมดใน stage 3/4", en: "% of total sleep in stage 3/4" },
  "an.latest": { th: "ล่าสุด", en: "Latest" },
  "an.baseline.title": { th: "ค่าฐานปัจจุบัน เทียบกับค่าเฉลี่ย 30 วัน", en: "Current Baseline vs. Past 30-Day Average" },
  "an.baseline.sub": { th: "ทิศทางที่ดีขึ้นขึ้นอยู่กับตัวชี้วัด", en: "Positive direction depends on the metric" },
  "an.baseline.improving": { th: "{count}/{total} ดีขึ้น", en: "{count}/{total} improving" },
  "an.baseline.avg30": { th: "ค่าเฉลี่ย 30 วัน: {value}{unit}", en: "30-day avg: {value}{unit}" },
  "an.metric.burnout": { th: "ความเสี่ยงหมดไฟ", en: "Burnout Risk" },
  "an.metric.faa": { th: "ดัชนี FAA", en: "FAA Index" },
  "an.metric.spindle": { th: "ความหนาแน่น Sleep Spindle", en: "Sleep Spindle Density" },
  "an.metric.sws": { th: "การนอนคลื่นช้า", en: "Slow-Wave Sleep" },
  "an.tip.title": { th: "แนวโน้มเชิงลึกจาก AI", en: "AI Trend Insight" },
  "an.tip.offline": { th: "ค่าประมาณออฟไลน์", en: "Offline estimate" },
  "an.tip.live": { th: "AI สด", en: "AI live" },
  "an.tip.offlineTitle": { th: "ค่าประมาณ rule-based ในเครื่อง (DeepSeek ออฟไลน์)", en: "Local rule-based estimate (DeepSeek offline)" },
  "an.tip.liveTitle": { th: "สร้างโดย DeepSeek AI", en: "Generated by DeepSeek AI" },
  "an.tip.loading": { th: "กำลังสรุปรวมแนวโน้มด้วย AI…", en: "Summarizing trends with AI…" },
  "an.tip.error": { th: "ยังไม่มีสรุปในขณะนี้", en: "No summary available right now" },
  "an.tip.unauth": { th: "เข้าสู่ระบบเพื่อให้ AI สรุปแนวโน้มสุขภาพสมองของคุณ", en: "Sign in to let AI summarize your brain-health trends" },
  "an.tip.nodata": { th: "ข้อมูลยังไม่เพียงพอที่จะสรุปแนวโน้ม", en: "Not enough data yet to summarize trends" },
  "an.tip.fbImproving": { th: "แนวโน้มสุขภาพสมองโดยรวมของคุณกำลังดีขึ้นในช่วง 30 วันที่ผ่านมา", en: "Your overall brain-health trend is improving over the past 30 days" },
  "an.tip.fbFlat": { th: "แนวโน้มสุขภาพสมองโดยรวมของคุณยังทรงตัวหรือผสมกันในช่วง 30 วันที่ผ่านมา", en: "Your overall brain-health trend is holding steady or mixed over the past 30 days" },
  "an.tip.fbTail": { th: "คำแนะนำเบื้องต้น: ควรติดตามตัวชี้วัดอย่างต่อเนื่องและพิจารณาปรึกษาผู้เชี่ยวชาญหากพบความผันผวนผิดปกติ (ข้อมูลนี้เป็นเพียงการคัดกรองเบื้องต้น ไม่ใช่การวินิจฉัย)", en: "Preliminary advice: keep tracking these indicators and consider consulting a specialist if you notice abnormal fluctuations (this is preliminary screening, not a diagnosis)" }
`;

const anchor = 'en: "All stages" }\n\n};';
if (!src.includes(anchor)) {
  console.error("Anchor not found — aborting.");
  process.exit(1);
}

// House style: the whole dictionary is written without Thai tone marks
// (mai tho / mai ek / maitaikhu / phinthu, U+0E48–U+0E4B). Strip them so the
// new keys match the existing 229 keys exactly.
const normalized = BLOCK.replace(/[่-๋]/g, "");

const out = src.replace(anchor, 'en: "All stages" },\n' + normalized + "\n};");
writeFileSync(file, out, "utf8");
console.log("Inserted an.* keys.");
